name: Run Builds and Tests

on: [push, pull_request]

jobs:
  linux-build-latest-with-gcc:
    name: "Linux gcc-11"
    runs-on: ubuntu-24.04
    strategy: 
      matrix: 
        build64IDs: ["OFF", "ON"]  
    steps:
      - name: Install prerequisites
        run:  |
          sudo apt-get update
          sudo apt-get install ninja-build gcc-11 g++-11
          g++ --version

      - name: Checkout dhb
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: build library, 64 bit IDs turned ${{ matrix.build64IDs }}, run test
        run:  | 
          [ ! -d build ] && mkdir build
          cd build
          mkdir gcc
          cd gcc
          cmake -GNinja -DDHB_BUILD_TESTS=ON -DDHB_WITH_64BIT_IDS=${{ matrix.build64IDs }} -DCMAKE_CXX_COMPILER=g++-11 ../../
          ninja
          ./dhb_test

  macos-build-latest-with-clang:
    name: "macOS clang"
    runs-on: macos-14
    strategy: 
      matrix: 
        build64IDs: ["OFF", "ON"]
        useClang: ['true', 'false']
        
    steps:
      - name: Install prerequisites
        run: |
          brew install ninja
          brew install libomp
      
      - name: Install llvm
        if: matrix.useClang == 'true'
        run: |
          brew install llvm
  
      - name: Checkout dhb
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: build library, 64 bit IDs turned ${{ matrix.build64IDs }}, run test
        env:
          CC: ${{ matrix.useClang == 'true' && '/opt/homebrew/opt/llvm/bin/clang' || 'c99' }}
          CXX: ${{ matrix.useClang == 'true' && '/opt/homebrew/opt/llvm/bin/clang++' || 'c++' }}
        run:  | 
          [ ! -d build ] && mkdir build
          cd build
          mkdir clang
          cd clang
          cmake -GNinja -DDHB_BUILD_TESTS=ON -DDHB_WITH_64BIT_IDS=${{ matrix.build64IDs }} ../../
          ninja
          ./dhb_test
